port: 9109
metadata:     #metadata 中的这些key将会被放入到指标中, 调整这块的数据需要重启生效, 不应与 "eureka_instance", "eureka_application", "eureka_hostname", "eureka_status" 重复
  - hostname
  - branch
eurekas:
  - urls: http://eureka1.domain.com/,http://eureka2.domain.com/  #多个实例地址逗号分隔,当前集群里的eureka实例url,会同时读取这些实例的注册信息并互相覆盖
    name: instance_1    #每个集群的name应当不同
    pullInterval: 30s   #注册信息拉取周期
#  - urls: http://eureka.domain-xx.com/
#    name: instance_2
#    pullInterval: 10s
