apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-exporter
  name: eureka-exporter
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eureka-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: eureka-exporter
    spec:
      containers:
        - args:
            - -config.file=/opt/config.yaml
          command:
            - /eureka-exporter
          image: eureka-exporter:v0.1
          imagePullPolicy: Always
          name: exporter
          volumeMounts:
            - mountPath: /opt
              name: config-yaml
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      volumes:
        - configMap:
            defaultMode: 420
            name: eureka-exporter-config
          name: config-yaml