apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-exporter
  name: eureka-exporter
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eureka-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: eureka-exporter
    spec:
      containers:
        - args:
            - -config.file=/opt/config.yaml
          command:
            - /eureka-exporter
          image: eureka-exporter:v0.1
          imagePullPolicy: Always
          name: exporter
          volumeMounts:
            - mountPath: /opt
              name: config-yaml
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      volumes:
        - configMap:
            defaultMode: 420
            name: eureka-exporter-config
          name: config-yaml

---
apiVersion: v1
data:
  config.yaml: |-
    port: 80
    metadata: #optional, metadata中的这些key将会假如到指标labels中, 调整需要重启生效, 会被附加前缀: eureka_meta_xxx
      - custom_meta_key1 #其中包含的 - 会被替换为 _
      - custom_meta_key2 #如果各个eureka实例中需要获取不同的metadata key, merge后都写这里即可
      - custom_meta_key3
    eurekas:
      - urls: http://eureka1.domain.com/,http://eureka2.domain.com/  #如果设置多个URL则视为一个eureka集群,并同时从各个URL中拉取数据
        name: instance_1    #不可重复
        pullInterval: 30s   #注册信息拉取周期
      - urls: http://eureka3.domain.com/ #如果设置多个URL则视为一个eureka集群,并同时从各个URL中拉取数据
        name: instance_1    #不可重复
        pullInterval: 30s   #注册信息拉取周期
        security: #optional, only supported basic security
          basic:
            user: user_name
            password: pwd

kind: ConfigMap
metadata:
  name: eureka-exporter-config
  namespace: default
